package com.yourcompany.kafkasqlexplorer.service;

import com.yourcompany.kafkasqlexplorer.config.KafkaConfig;
import com.yourcompany.kafkasqlexplorer.domain.MessageFormat;
import org.apache.flink.streaming.api.environment.StreamExecutionEnvironment;
import org.apache.flink.table.api.EnvironmentSettings;
import org.apache.flink.table.api.bridge.java.StreamTableEnvironment;
import org.apache.flink.table.catalog.Column;
import org.apache.flink.table.catalog.ResolvedSchema;
import org.junit.jupiter.api.BeforeAll;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.TestInstance;

import java.util.LinkedHashMap;
import java.util.Map;
import java.util.stream.Collectors;

import static org.junit.jupiter.api.Assertions.*;

/**
 * Validates that the DDL generated by {@link DdlGeneratorService} is accepted by the embedded
 * Flink engine and produces the expected column structure.
 *
 * All DDL statements are registered in {@code @BeforeAll} so each {@code @Test} method can
 * inspect the resulting schema independently without inter-test ordering dependencies.
 *
 * Flink defers connector instantiation to query execution time, so {@code CREATE TABLE} succeeds
 * even without a live Kafka broker. This lets us verify:
 * <ul>
 *   <li>DDL syntax is valid for the Flink parser.</li>
 *   <li>Physical, METADATA, and computed columns are declared correctly.</li>
 *   <li>The "Unable to create a source" bug (METADATA FROM 'value' mixed with
 *       value.format='raw') is absent from the generated DDL.</li>
 * </ul>
 */
@TestInstance(TestInstance.Lifecycle.PER_CLASS)
class FlinkDdlValidationTest {

    private StreamTableEnvironment tableEnv;
    private DdlGeneratorService ddlGenerator;

    // Schemas resolved at setup time — inspected by individual tests
    private ResolvedSchema jsonSchema;
    private ResolvedSchema xmlSchema;
    private ResolvedSchema avroSchema;
    private ResolvedSchema autoSchema;

    @BeforeAll
    void setupFlinkAndRegisterTables() {
        StreamExecutionEnvironment env = StreamExecutionEnvironment.createLocalEnvironment();
        tableEnv = StreamTableEnvironment.create(env,
                EnvironmentSettings.newInstance().inStreamingMode().build());

        KafkaConfig kafkaConfig = new KafkaConfig();
        kafkaConfig.setBootstrapServers("localhost:9092");
        kafkaConfig.setSchemaRegistryUrl("http://localhost:8081");
        ddlGenerator = new DdlGeneratorService(kafkaConfig, new NamingConventionService());

        // JSON topic with user-defined fields
        Map<String, String> schema = new LinkedHashMap<>();
        schema.put("order_id", "STRING");
        schema.put("amount", "DOUBLE");
        schema.put("state", "STRING");
        tableEnv.executeSql(ddlGenerator.generateDdl("val.json.topic", schema, MessageFormat.JSON));
        jsonSchema = tableEnv.from("val_json_topic").getResolvedSchema();

        // Avro topic with user-defined fields
        Map<String, String> avroFields = new LinkedHashMap<>();
        avroFields.put("id", "INT");
        avroFields.put("name", "STRING");
        tableEnv.executeSql(ddlGenerator.generateDdl("val.avro.topic", avroFields, MessageFormat.AVRO));
        avroSchema = tableEnv.from("val_avro_topic").getResolvedSchema();

        // XML topic (no schema — raw_value is the only user column)
        tableEnv.executeSql(ddlGenerator.generateDdl("val.xml.topic", Map.of(), MessageFormat.XML));
        xmlSchema = tableEnv.from("val_xml_topic").getResolvedSchema();

        // AUTO topic with empty schema (topic empty or format undetectable)
        tableEnv.executeSql(ddlGenerator.generateDdl("val.auto.topic", Map.of(), MessageFormat.AUTO));
        autoSchema = tableEnv.from("val_auto_topic").getResolvedSchema();

        // Topic with dots → sanitized name
        tableEnv.executeSql(ddlGenerator.generateDdl("demo.orders.1.received",
                Map.of("id", "STRING"), MessageFormat.JSON));

        // Topic with hyphens → sanitized name
        tableEnv.executeSql(ddlGenerator.generateDdl("my-topic-name",
                Map.of("event_type", "STRING"), MessageFormat.JSON));
    }

    // ──────────────────────────────────────────────────────────────────────────────
    // JSON format — column types
    // ──────────────────────────────────────────────────────────────────────────────

    @Test
    void jsonDdlUserColumnsArePhysical() {
        Map<String, Column> cols = byName(jsonSchema);
        assertTrue(cols.get("order_id").isPhysical(), "order_id must be a physical column");
        assertTrue(cols.get("amount").isPhysical(), "amount must be a physical column");
        assertTrue(cols.get("state").isPhysical(), "state must be a physical column");
    }

    @Test
    void avroDdlUserColumnsArePhysical() {
        Map<String, Column> cols = byName(avroSchema);
        assertTrue(cols.get("id").isPhysical(), "id must be a physical column");
        assertTrue(cols.get("name").isPhysical(), "name must be a physical column");
    }

    @Test
    void jsonDdlHasNoRawValueColumn() {
        // The Kafka connector does NOT support 'value' as a metadata key.
        // Adding "raw_value BYTES METADATA FROM 'value' VIRTUAL" causes
        // "Unable to create a source" at SELECT time. The JSON DDL must NOT include
        // such a column — user data is accessed via the physical JSON-decoded columns.
        Column rawValue = byName(jsonSchema).get("raw_value");
        assertNull(rawValue,
                "JSON DDL must NOT declare a raw_value column. " +
                "'METADATA FROM ''value''' is not supported by the Kafka connector " +
                "and causes 'Unable to create a source'.");
    }

    @Test
    void jsonDdlProcTimeIsComputedColumn() {
        Column procTime = byName(jsonSchema).get("proc_time");
        assertNotNull(procTime, "proc_time must exist");
        assertInstanceOf(Column.ComputedColumn.class, procTime,
                "proc_time must be a computed column (AS PROCTIME())");
    }

    @Test
    void jsonDdlEventTimeIsMetadataColumn() {
        Column eventTime = byName(jsonSchema).get("event_time");
        assertNotNull(eventTime, "event_time must exist");
        assertInstanceOf(Column.MetadataColumn.class, eventTime,
                "event_time must be a METADATA column (METADATA FROM 'timestamp')");
    }

    // ──────────────────────────────────────────────────────────────────────────────
    // XML format — raw_value must be physical, NOT metadata
    // ──────────────────────────────────────────────────────────────────────────────

    @Test
    void xmlDdlRawValueIsPhysicalColumn() {
        // CRITICAL: For XML (value.format='raw'), raw_value MUST be a physical column.
        // Declaring it as METADATA FROM 'value' is incompatible with value.format='raw'
        // and causes "Unable to create a source" at SELECT time.
        Column rawValue = byName(xmlSchema).get("raw_value");
        assertNotNull(rawValue, "raw_value must exist in XML DDL");
        assertInstanceOf(Column.PhysicalColumn.class, rawValue,
                "raw_value must be PHYSICAL for XML format — METADATA FROM 'value' is " +
                "incompatible with value.format='raw'.");
    }

    @Test
    void xmlDdlProcTimeAndEventTimeExist() {
        Map<String, Column> cols = byName(xmlSchema);
        assertInstanceOf(Column.ComputedColumn.class, cols.get("proc_time"),
                "proc_time must be ComputedColumn for XML DDL");
        assertInstanceOf(Column.MetadataColumn.class, cols.get("event_time"),
                "event_time must be MetadataColumn for XML DDL");
    }

    // ──────────────────────────────────────────────────────────────────────────────
    // AUTO format — defaults to JSON (not raw)
    // ──────────────────────────────────────────────────────────────────────────────

    @Test
    void autoDdlDefaultsToJsonNotRaw() {
        // AUTO with empty schema must use format='json', NOT format='raw'.
        // If it used format='raw', it would require a physical raw_value column AND would
        // cause "Unable to create a source" for topics containing JSON content.
        // With format='json' + json.ignore-parse-errors=true, zero physical columns is valid:
        // Flink simply produces null for all fields. The user can still query event_time / proc_time.
        // Verify: no raw_value physical column (which would indicate format='raw' was used).
        Column rawValue = byName(autoSchema).get("raw_value");
        assertNull(rawValue,
                "AUTO DDL must NOT have a raw_value physical column — that would indicate " +
                "format='raw' was used, which causes 'Unable to create a source' for JSON topics.");
    }

    // ──────────────────────────────────────────────────────────────────────────────
    // Topic name sanitization
    // ──────────────────────────────────────────────────────────────────────────────

    @Test
    void dotSeparatedTopicNameIsSanitizedToUnderscores() {
        // "demo.orders.1.received" → table "demo_orders_1_received"
        assertDoesNotThrow(
                () -> tableEnv.from("demo_orders_1_received").getResolvedSchema(),
                "Dot-separated topic must be registered as an underscore table name");
    }

    @Test
    void hyphenatedTopicNameIsSanitizedToUnderscores() {
        assertDoesNotThrow(
                () -> tableEnv.from("my_topic_name").getResolvedSchema(),
                "Hyphenated topic must be registered as an underscore table name");
    }

    // ──────────────────────────────────────────────────────────────────────────────
    // SQL injection prevention in startup mode
    // ──────────────────────────────────────────────────────────────────────────────

    @Test
    void invalidStartupModeFallsBackToEarliestOffset() {
        Map<String, String> schema = Map.of("id", "STRING");
        String ddl = ddlGenerator.generateDdl("ddlval.startup.topic", schema, MessageFormat.JSON,
                "'; DROP TABLE foo; --");

        assertTrue(ddl.contains("'scan.startup.mode' = 'earliest-offset'"),
                "An injected startup mode value must be replaced by 'earliest-offset'");
        // DDL must still be parseable
        assertDoesNotThrow(() -> tableEnv.executeSql(ddl));
    }

    // ──────────────────────────────────────────────────────────────────────────────
    // Helper
    // ──────────────────────────────────────────────────────────────────────────────

    private Map<String, Column> byName(ResolvedSchema schema) {
        return schema.getColumns().stream()
                .collect(Collectors.toMap(Column::getName, c -> c));
    }
}
